### PR TITLE
Improve library history parsing

### PR DESCRIPTION
**Pull request by FoxxMD**
* Check for list structure to avoid intermittent "undefined" structures foxxmd/multi-scrobbler#86
* Include all recently played regardless of time slice for a more complete list

### CODE REVIEW

**Comment by FoxxMD** [comment]
Hey, can this get merged?

**Comment by Nikey646** [comment]
+1

**Comment by nickp10** [comment]
I have merged this as-is. I don't know how everyone intends to use this getLibraryHistory function, but it may be worth considering leaving the tracks split into the separate categories as opposed to joining them into one array. For now, it will be left as one combined array.

**Comment by FoxxMD** [comment]
It may be worth adding an argument to allow user to define how they'd like the list returned. 

The main motivation for this change, though, is that the structure (array/object) of the history is relative to the time it is queried at which makes it inconsistent unless your app is also keeping track of that relative time to account for it. As an example:

On Day 9/30 at 11:59 `getLibraryHistory` returns:

* Today (empty)
* Yesterday
  * Track 1
  * Track 2
* Day 9/28
  * Track 3
  * Track 4
...
* Last Week
  * Track 5
  * Track 6


On Day 10/1 at 00:00 `getLibraryHistory` returns:

* Today (empty)
* Yesterday (empty or possibly undefined)
* Day 9/29
  * Track 1
  * Track 2
* Day 9/28
  * Track 3
  * Track 4
...
* Last Week (no longer defined)
* Last Month
  * Track 5
  * Track 6

___

This is pretty hard to deal with and the root problem of foxxmd/multi-scrobbler#86 . Changing this to return a flat list means returned results are consistent. I think it's better to have the consistent result as the default and if anyone really wants the relative-time sliced view in the future they can add a param to get that.

**Pull request merged**
